### ISSUE TITLE
Cannot import spconv in the 3D-U-Net repo

### ISSUE THREAD

**Issue by NCTU-VRDL** [liuzhengzhe/One-Thing-One-Click#11]
Hi @liuzhengzhe!,

I have followed all the steps to successfully install the `spconv` and import it without any problems, including `from spconv import spconv_utils`. However, I cannot import `spconv` inside the model repo (3D-U-Net, merge, relation). The error message is shown below.
```
     15 import numpy as np
---> 16 from spconv import spconv_utils
     17 from spconv.spconv_utils import (non_max_suppression, non_max_suppression_cpu,
     18                                  points_to_voxel_3d_np, rbbox_iou,

ImportError: cannot import name 'spconv_utils' from 'spconv' (/home/jimmy15923/mnt/project_code/One-Thing-One-Click/3D-U-Net/spconv/__init__.py)
```

And I can import `spconv` in the upper repo. Should I remove the original `spconv` after installation? Thank you

![image](https://user-images.githubusercontent.com/55061120/137864678-9bd61788-6fd7-4906-a6e7-c1a2898bdf7a.png)

**Comment by liuzhengzhe** [comment]
Yes, you can replace this folder with your newly built one (in
spconv/build/...)

NCTU-VRDL ***@***.***> 于2021年10月19日周二 下午3:39写道：
