### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by argosdh** [liuzhengzhe/One-Thing-One-Click#13]
Hi, I was checking the code. I found out that you choose the random segment of each instance to be annotated(https://github.com/liuzhengzhe/One-Thing-One-Click/blob/6b452493727e8fe813c85a97e6e1876767c4c053/data/prepare_data_otoc.py#L95). And at the end of this function you set all points in this segment to be annotated. For example, at scene0000_00, there are 67 instances in total, from my perspective, only 67 points should be annotated. I calculated len(np.where(sem_labels!=-100)[0]) for this scan and I found that there are 15468 points with label. I also visualized the point cloud and found it is very different from figure in paper. I think what the code did is keeping one segment of each instance but not keeping only one single point of it. Is this because later you need to propagate the one labled point to the corresponding super voxel(as segment now). So this operation is equivalent to what I described above?

**Comment by liuzhengzhe** [comment]
Hi, the segment is our super voxel. We annotate the points, and then
propagate the annotated point to the whole super voxel it belongs to.

Please note that the super voxel propagation itself may cause some error
(it not happen in scannet, but happen in S3DIS).

argosdh ***@***.***> 于2021年11月12日周五 下午6:57写道：

**Comment by argosdh** [comment]
Ok, I understand. I have one more question. Mesh segmentation segments the whole scene to hundreds of different segments. These segments information is in file xxxxx._vh_clean_2.0.010000.segs.json'. And file '.aggregation.json' provides groups of segments indices which are components of instances. Here is an assumption: we assume that each super voxel(or mesh segment) only contain part of one specific instance. I mean, there won't be any super voxel which cross different instances. Is this correct?

**Comment by argosdh** [comment]
I checked all segments, all points in a segment shares same instance label. So the assumption is correct.

**Comment by liuzhengzhe** [comment]
For scannet,  all points in a segment shares same instance label, but for
S3DIS,  it is not the case.

argosdh ***@***.***> 于2021年11月13日周六 下午4:03写道：
