### ISSUE TITLE
About S3DIS

### ISSUE THREAD

**Issue by iris0329** [liuzhengzhe/One-Thing-One-Click#15]
Hi Liu,
Do you and your team have any plan to open source the code on S3DIS (ei. data pre process)? Or could you give some idea about how to reproduce it? Many thanks.

**Comment by liuzhengzhe** [comment]
Thanks for your message. We will open source S3DIS very soon. In our new
version, we got 56% mIoU on S3DIS, which is better than the original
version (50.1%).

Iris ***@***.***> 于2021年12月21日周二 14:09写道：

**Comment by iris0329** [comment]
Thank you Liu

**Comment by liuzhengzhe** [comment]
Hi, we have released the code on S3DIS.
