### ISSUE TITLE
About spatial_shape clip

### ISSUE THREAD

**Issue by iris0329** [liuzhengzhe/One-Thing-One-Click#16]
Hi Liu,

In your config file, it has `full_scale: [128, 512]`, 

and in the trainMerge(), it has `spatial_shape = np.clip((locs.max(0)[0][1:] + 1).numpy(), self.full_scale[0], None) `

Could you tell me why do you need to clip the `locs` with the limitation of 128? Thank you~

**Comment by liuzhengzhe** [comment]
Thanks for your message.

We directly follow the setting in PointGroup (
https://github.com/dvlab-research/PointGroup), and did not change the
parameters.

Iris ***@***.***> 于2021年12月28日周二 11:12写道：

**Comment by iris0329** [comment]
Okay, Thank you.
