### ISSUE TITLE
About two .so files: "libspconv.so" and "spconv_utils.so"

### ISSUE THREAD

**Issue by baixiao930** [liuzhengzhe/One-Thing-One-Click#2]
Thanks for your great work. I met some problems at the step of training (the installation and compilation steps have been completed without problems).  My environment is set the same as README, and spconv has been compiled and installed. 

The code seems to require two .so files, "libspconv.so" and "spconv_utils.so". But I only found "libspconv_nms.so.1.0" and "spconv_utils.cpython-37m-x86_64-linux-gnu.so.1.0" at "One-Thing-One-Click/3D-U-Net/spconv". 
So when I run "python train.py --config config/pointgroup_run1_scannet.yaml", it raised two errors as below:

OSError: /home/xxx/One-Thing-One-Click/3D-U-Net/spconv/libspconv.so: cannot open shared object file: No such file or directory
at File "train.py", line 141, in <module>
    from model.pointgroup.pointgroup import PointGroup as Network
  File "/home/xxx/One-Thing-One-Click/3D-U-Net/model/pointgroup/pointgroup.py", line 9, in <module>
    import spconv
  File "/home/xxx/One-Thing-One-Click/3D-U-Net/spconv/__init__.py", line 27, in <module>
    torch.ops.load_library(_LIB_PATH)

and, 

ImportError: cannot import name 'spconv_utils' from 'spconv' (/home/xxx/One-Thing-One-Click/3D-U-Net/spconv/__init__.py)
at File "train.py", line 141, in <module>
    from model.pointgroup.pointgroup import PointGroup as Network
  File "/home/xxx/One-Thing-One-Click/3D-U-Net/model/pointgroup/pointgroup.py", line 9, in <module>
    import spconv
  File "/home/xxx/One-Thing-One-Click/3D-U-Net/spconv/__init__.py", line 19, in <module>
    from spconv import utils
  File "/home/xxx/One-Thing-One-Click/3D-U-Net/spconv/utils/__init__.py", line 16, in <module>
    from spconv import spconv_utils

Could you give some advice on how to fix these errors? Thanks for your time.

**Comment by liuzhengzhe** [comment]
Hi, you can copy lib/spconv/build/lib.linux-x86_64-3.7/spconv/ to your main project folder. 

![捕获](https://user-images.githubusercontent.com/8349580/120254019-6ee36000-c2bb-11eb-8777-965017616030.PNG)

**Comment by baixiao930** [comment]
Thanks very much! It works. 

Would you please share more detailed hyperparameters on the dataset ScanNet and S3DIS? 
especially, the voxel scale and the batchsize.

**Comment by liuzhengzhe** [comment]
The hyperparameters in the repo is okay (like following). In the 1st iteration (train 512 iters), the performance of 3D U-Net without any post-processing (super voxel, CRF, relation-net) should be around 59%. If you can achieve this performance, then hyper-parameters are correct. After post-processing it should be around 61%.  If your result is lower than it, you may weaken CRF in inference in the 1st, 2nd iterations. 

In addition, in the 2nd, 3rd iterations, we fine-tune the model of first iteration to shorten the training time.


ScanNet:
  classes: 20
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 3
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: pointgroup
  m: 32 # 16 or 32
  block_residual: True
  block_reps: 2

  use_coords: True

TRAIN:
  epochs: 1280
  train_workers: 1 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.01
  step_epoch: 1024
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 16  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

GROUP:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_epochs: 128

TEST:
  split: val
  test_epoch: 384
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100


S3DIS:

  classes: 13
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 4
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: pointgroup
  m: 32 # 16 or 32
  block_residual: True
  block_reps: 2

  use_coords: True

TRAIN:
  epochs: 3200
  train_workers: 16 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.01
  step_epoch: 2500
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 16  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

**Comment by baixiao930** [comment]
Thank you very much! Another small question is, for the fully supervised baseline, does these hyperparameters work as well?

**Comment by liuzhengzhe** [comment]
Yes, they also work for fully-sup setting.

baixiao930 ***@***.***> 于2021年7月20日周二 上午10:37写道：
