### ISSUE TITLE
About relation net

### ISSUE THREAD

**Issue by chendaozai** [liuzhengzhe/One-Thing-One-Click#22]
Hi，I have problem is why not just use the features of 3D unet directly? It takes a lot of time to train an extra unet.Have you done any related experiments?

**Comment by liuzhengzhe** [comment]
Hi, you can also use this feature directly and it can also produce the reasonable result. 

An extra U-Net is not a necessity, but can further improve the performance.

**Comment by chendaozai** [comment]
Thanks a lot for your reply!
