### ISSUE TITLE
About Super-voxel pooling

### ISSUE THREAD

**Issue by chendaozai** [liuzhengzhe/One-Thing-One-Click#26]
Hello! Thank you for a very nice job! I want to know about the implementation part of the ```super-voxel pooling```, where is the code implementation for this part?

**Comment by liuzhengzhe** [comment]
Please see "s3dis" folder.

Super-voxel for scannet-v2 are provided by the author of scannet-v2.

chendaozai ***@***.***> 于2022年10月29日周六 22:22写道：
