### ISSUE TITLE
About `s3dis/data/concate_new.py`

### ISSUE THREAD

**Issue by chendaozai** [liuzhengzhe/One-Thing-One-Click#27]
Hellow， I have a problem about `concate_new.py` .In this code, why do you concatenate all the point clouds in the annotation file?S3DIS provides room points txt file.

**Comment by liuzhengzhe** [comment]
The point order is not consistent in the separated file and the whole scene
file. If we directly use the given file to train the model, the results are
very poor. Hence, I define my own order to ensure that the point order is
consistent.

Zhengzhe

chendaozai ***@***.***> 于2023年1月17日周二 21:24写道：

**Comment by chendaozai** [comment]
OK! Thanks!
