### ISSUE TITLE
About spg on s3dis

### ISSUE THREAD

**Issue by chendaozai** [liuzhengzhe/One-Thing-One-Click#28]
Happy Chinese New Year,
I would like to know if you have modified the plc_c.cpp in otoc?

**Comment by chendaozai** [comment]
The file path is `otoc/s3dis/data/partition/ply_c/ply_c.cpp`.

**Comment by liuzhengzhe** [comment]
Yes, I have modified it.

We need to know how to map from each point to each voxel. Key is point
index, and value is voxel index, which is not provided by the original
code.

Zhengzhe

chendaozai ***@***.***> 于2023年1月27日周五 10:27写道：

**Comment by chendaozai** [comment]
Ok, thanks. I will recompile it.

**Comment by chendaozai** [comment]
@liuzhengzhe Hello, I would also like to know if the group id is unique to the whole scene.
And what this line of code means？https://github.com/liuzhengzhe/One-Thing-One-Click/blob/6f65946284d35da93db6145bea537e854a96076e/s3dis/data/sup_voxel.py#L147****
