### ISSUE TITLE
Looking forward to your One Thing One Click++code

### ISSUE THREAD

**Issue by HQ000** [liuzhengzhe/One-Thing-One-Click#30]
I have read your latest article.Looking forward to your One Thing One Click++ code.

**Comment by liuzhengzhe** [comment]
I have already released codes in this repository. Please have a look
"instance_seg" folder

Zhengzhe

HQ000 ***@***.***> 于2023年4月9日周日 11:07写道：

**Comment by HQ000** [comment]
Thank you.
