### ISSUE TITLE
Point Cloud Super-Voxelization

### ISSUE THREAD

**Issue by rkjones4** [liuzhengzhe/One-Thing-One-Click#4]
Hi, very cool project!

A quick question: Can you please provide a pointer to the code that calculates the super-voxel partitioning of the input point cloud? 

Thank you!

**Comment by liuzhengzhe** [comment]
Scannet provide the super vodel officially:
https://github.com/ScanNet/ScanNet/tree/master/Segmentator

and they provide it in the file xxxxx.'_vh_clean_2.0.010000.segs.json'

rkjones4 ***@***.***> 于2021年9月14日周二 下午9:00写道：
