### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by wu-zhonghua** [liuzhengzhe/One-Thing-One-Click#5]
Thus can you please give your official testing code?

I have used the test.py to test your pre-trained model (pointgroup_run1_scannet-000001250.pth). I have used intersectionAndUnion function that I want to calculate the IoU for each sample. It seems the performance it's very poor, like only 53.36 mIoU, while you said it should be 68.96. Thus can you please give your official testing code? Many thanks.

**Comment by liuzhengzhe** [comment]
Thanks for your message. 

You can use the attached evaluate.py:

python evaluate.py --pred_path result/pred --gt_path /your_gt_path

[evaluate.zip](https://github.com/liuzhengzhe/One-Thing-One-Click/files/7203635/evaluate.zip)

I double-checked it, and the results should be like this:

i 0 wall (0.8205671084484125, 10312368, 12567367)
i 1 floor (0.9466665252818084, 8838286, 9336219)
i 2 cabinet (0.6209790633913489, 1044357, 1681791)
i 3 bed (0.76602249326786, 725385, 946950)
i 4 chair (0.8626431680578681, 2960424, 3431806)
i 5 sofa (0.8015485298184164, 704376, 878769)
i 6 table (0.7141122980096437, 1204194, 1686281)
i 7 door (0.6241241117669895, 1188107, 1903639)
i 8 window (0.6199183641927793, 1026821, 1656381)
i 9 bookshelf (0.7668615518278953, 962093, 1254585)
i 10 picture (0.3238335791158106, 103209, 318710)
i 11 counter (0.6145707998226838, 155275, 252656)
i 12 desk (0.6367950196991794, 497335, 780997)
i 13 curtain (0.699687692035726, 498708, 712758)
i 14 refrigerator (0.5135724573635798, 125513, 244392)
i 15 shower curtain (0.6463215099631859, 110605, 171130)
i 16 toilet (0.8916129145034698, 102013, 114414)
i 17 sink (0.5856695508858674, 71071, 121350)
i 18 bathtub (0.8490641417470686, 85010, 100122)
i 19 otherfurniture (0.46748377496827076, 907954, 1942215)
wrote results to result/pred/semantic_label_evaluation.txt
avg iou:  0.6886027327083932
